### ISSUE TITLE
Getting ImportError, even after adding pwd to PYTHONPATH env variable

### ISSUE THREAD

**Issue by wakeuprj** [successar/AttentionExplanation#3]
![image](https://user-images.githubusercontent.com/17407036/58039123-bb6eff00-7b29-11e9-9a11-a35425462c47.png)

**Comment by successar** [comment]
Just to confirm -- Can you import `import Transparency` and `import Transparency.model` ? If yes, the problem could that I didn't add `__init__.py` files in other folder I import from . I have added them now. Please update your clone and let me know if it works.

**Comment by wakeuprj** [comment]
Added this to the train_and_run_experiments_bc.py and it worked.
```
import sys

sys.path.append('/Users/location-of-Transparency-dir/')
```
