### ISSUE TITLE
Some clarification regarding QA experiments

### ISSUE THREAD

**Issue by svjan5** [successar/AttentionExplanation#4]
Hi Sarthak,
I am finding it hard to understand that how the value of `output_size` over [here](https://github.com/successar/AttentionExplanation/blob/master/model/modules/Decoder.py#L98) is coming out to be `36` for `babI` dataset with encoder as `lstm`. Can you please provide an explanation?

Thanks in advance

**Comment by successar** [comment]
The babI dataset have in total 40 entities that can be predicted for Tasks 1/2/3 (that is also the size of vocabulary). But not all tasks have all 40 entities present.

**Comment by svjan5** [comment]
got it, thanks a lot!
